#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Train a latent-to-latent depth head for Wan2.2.

The head maps VAE-encoded RGB video latents -> VAE-encoded depth latents.
It does not influence video generation and can be trained independently.

Expected dataset:
  - Videos: dataset_base_path/<video>.mp4
  - Depth:  dataset_geometry_path/<video_stem>.npz (point_map + mask)
- Metadata: optional CSV. If omitted, the script scans dataset_base_path for videos and pairs them with dataset_geometry_path/<stem>.npz.

Outputs:
  - Safetensors checkpoints under output_path (epoch-*.safetensors)
"""

import os
import glob
import argparse
import json
import csv
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
from torch.utils.data import DataLoader
from torch.utils.data.distributed import DistributedSampler

from accelerate import Accelerator

from diffsynth.core.data.unified_dataset import UnifiedDataset
from diffsynth.pipelines.wan_video_new import WanVideoPipeline, ModelConfig
from diffsynth.models.wan_video_latent_depth_head import WanLatentDepthHead


def _sorted_ckpts(pattern: str) -> List[str]:
    files = glob.glob(pattern)
    if not files:
        raise FileNotFoundError(f"No checkpoints found for pattern: {pattern}")

    def _key(p: str):
        name = os.path.basename(p)
        m = None
        try:
            import re

            m = re.search(r"-(\d+)-of-(\d+)", name)
        except Exception:
            m = None
        return (int(m.group(1)) if m else 0, p)

    return sorted(files, key=_key)


def _build_model_configs(model_id: str, model_root: Optional[str]) -> List[ModelConfig]:
    if model_root and os.path.isdir(model_root):
        hi = _sorted_ckpts(os.path.join(model_root, "high_noise_model", "diffusion_pytorch_model*.safetensors"))
        lo = _sorted_ckpts(os.path.join(model_root, "low_noise_model", "diffusion_pytorch_model*.safetensors"))
        t5 = os.path.join(model_root, "models_t5_umt5-xxl-enc-bf16.pth")
        vae = os.path.join(model_root, "Wan2.1_VAE.pth")
        if not os.path.isfile(t5):
            raise FileNotFoundError(f"Missing T5 file: {t5}")
        if not os.path.isfile(vae):
            raise FileNotFoundError(f"Missing VAE file: {vae}")
        return [
            ModelConfig(path=hi, offload_device="cpu"),
            ModelConfig(path=lo, offload_device="cpu"),
            ModelConfig(path=t5, offload_device="cpu"),
            ModelConfig(path=vae, offload_device="cpu"),
        ]

    return [
        ModelConfig(model_id=model_id, origin_file_pattern="high_noise_model/diffusion_pytorch_model*.safetensors", offload_device="cpu"),
        ModelConfig(model_id=model_id, origin_file_pattern="low_noise_model/diffusion_pytorch_model*.safetensors", offload_device="cpu"),
        ModelConfig(model_id=model_id, origin_file_pattern="models_t5_umt5-xxl-enc-bf16.pth", offload_device="cpu"),
        ModelConfig(model_id=model_id, origin_file_pattern="Wan2.1_VAE.pth", offload_device="cpu"),
    ]


def _collate(batch: List[Dict[str, Any]]) -> Dict[str, Any]:
    videos = [b["video"] for b in batch]
    depths = [b.get("depth") for b in batch]
    return {"video": videos, "depth": depths}


def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument("--dataset_base_path", type=str, required=True)
    parser.add_argument("--dataset_geometry_path", type=str, required=True)
    parser.add_argument("--dataset_metadata_path", type=str, default=None, help="Optional CSV metadata. If omitted, an auto metadata CSV will be generated by scanning dataset_base_path.")
    parser.add_argument("--data_file_keys", type=str, default="video")

    parser.add_argument("--model_id", type=str, default="Wan-AI/Wan2.2-I2V-A14B")
    parser.add_argument("--model_root", type=str, default=None)

    parser.add_argument("--height", type=int, default=320)
    parser.add_argument("--width", type=int, default=368)
    parser.add_argument("--num_frames", type=int, default=145)

    parser.add_argument("--tiled", action="store_true", default=True)
    parser.add_argument("--tile_size", type=str, default="30,52")
    parser.add_argument("--tile_stride", type=str, default="15,26")

    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--dataset_repeat", type=int, default=1)

    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument("--num_epochs", type=int, default=5)
    parser.add_argument("--grad_accum_steps", type=int, default=1)

    parser.add_argument("--hidden_channels", type=int, default=256)
    parser.add_argument("--output_path", type=str, required=True)
    parser.add_argument("--save_every_epochs", type=int, default=1)
    parser.add_argument("--resume_ckpt", type=str, default=None)

    args = parser.parse_args()

    accelerator = Accelerator(gradient_accumulation_steps=int(args.grad_accum_steps))

    os.makedirs(args.output_path, exist_ok=True)

    if args.dataset_metadata_path is None or str(args.dataset_metadata_path).strip() == "":
        auto_meta = os.path.join(args.output_path, "auto_metadata.csv")
        if accelerator.is_main_process:
            video_exts = (".mp4", ".mov", ".avi", ".mkv")
            pairs: List[str] = []
            base = os.path.abspath(args.dataset_base_path)
            for root, _, files in os.walk(base):
                for fn in files:
                    if not fn.lower().endswith(video_exts):
                        continue
                    abs_video = os.path.join(root, fn)
                    rel_video = os.path.relpath(abs_video, base).replace("\\", "/")
                    stem = Path(rel_video).stem
                    depth_path = os.path.join(args.dataset_geometry_path, f"{stem}.npz")
                    if os.path.isfile(depth_path):
                        pairs.append(rel_video)
            pairs.sort()
            if not pairs:
                raise RuntimeError(
                    f"No matched video-depth pairs found. base_path={args.dataset_base_path} geometry_path={args.dataset_geometry_path}"
                )
            with open(auto_meta, "w", encoding="utf-8", newline="") as f:
                w = csv.writer(f)
                w.writerow(["video"])
                for v in pairs:
                    w.writerow([v])
            print(f"[data] Auto metadata written: {auto_meta} | pairs={len(pairs)}")
        accelerator.wait_for_everyone()
        args.dataset_metadata_path = auto_meta


    tile_size = tuple(int(x) for x in str(args.tile_size).split(","))
    tile_stride = tuple(int(x) for x in str(args.tile_stride).split(","))

    data_file_keys = [x.strip() for x in str(args.data_file_keys).split(",") if x.strip()]
    if "video" not in data_file_keys:
        data_file_keys.append("video")

    dataset = UnifiedDataset(
        base_path=args.dataset_base_path,
        geometry_path=args.dataset_geometry_path,
        metadata_path=args.dataset_metadata_path,
        data_file_keys=data_file_keys,
        height=int(args.height),
        width=int(args.width),
        height_division_factor=16,
        width_division_factor=16,
        num_frames=int(args.num_frames),
        time_division_factor=4,
        time_division_remainder=1,
        repeat=int(args.dataset_repeat),
    )

    sampler = None
    if accelerator.num_processes > 1:
        sampler = DistributedSampler(dataset, shuffle=True)

    loader = DataLoader(
        dataset,
        batch_size=int(args.batch_size),
        shuffle=(sampler is None),
        sampler=sampler,
        num_workers=int(args.num_workers),
        pin_memory=True,
        drop_last=False,
        collate_fn=_collate,
    )

    model_configs = _build_model_configs(args.model_id, args.model_root)
    pipe = WanVideoPipeline.from_pretrained(
        torch_dtype=torch.bfloat16,
        device=accelerator.device,
        model_configs=model_configs,
    )
    pipe.enable_vram_management()

    z_dim = None
    if getattr(pipe, "vae", None) is not None and hasattr(pipe.vae, "model") and hasattr(pipe.vae.model, "z_dim"):
        z_dim = int(pipe.vae.model.z_dim)
    if z_dim is None:
        raise RuntimeError("Failed to infer VAE z_dim.")

    head = WanLatentDepthHead(in_channels=z_dim, out_channels=z_dim, hidden_channels=int(args.hidden_channels)).to(device=accelerator.device)

    if args.resume_ckpt:
        from safetensors.torch import load_file

        sd = load_file(args.resume_ckpt, device="cpu")
        head.load_state_dict(sd, strict=False)
        accelerator.print(f"Resumed from {args.resume_ckpt}")

    optimizer = torch.optim.AdamW(head.parameters(), lr=float(args.learning_rate), weight_decay=float(args.weight_decay))

    head, optimizer, loader = accelerator.prepare(head, optimizer, loader)

    pipe.load_models_to_device([])
    pipe.vae.eval()
    for p in pipe.vae.parameters():
        p.requires_grad = False

    loss_fn = torch.nn.MSELoss()

    def encode_depth_to_latents(depth_b1thw: torch.Tensor) -> torch.Tensor:
        depth = depth_b1thw
        if depth.dim() == 4:
            depth = depth.unsqueeze(0)
        if depth.shape[1] == 1:
            depth = depth.repeat(1, 3, 1, 1, 1)
        pipe.load_models_to_device(["vae"])
        with torch.no_grad():
            return pipe.vae.encode(depth, device=accelerator.device, tiled=bool(args.tiled), tile_size=tile_size, tile_stride=tile_stride)

    def encode_video_to_latents(video_frames: List[List[Any]]) -> torch.Tensor:
        pipe.load_models_to_device(["vae"])
        with torch.no_grad():
            vids: List[torch.Tensor] = []
            for frames in video_frames:
                v = pipe.preprocess_video(frames, torch_dtype=pipe.torch_dtype, device=accelerator.device)
                vids.append(v)
            video = torch.cat(vids, dim=0)
            return pipe.vae.encode(video, device=accelerator.device, tiled=bool(args.tiled), tile_size=tile_size, tile_stride=tile_stride)

    for epoch in range(1, int(args.num_epochs) + 1):
        if sampler is not None:
            sampler.set_epoch(epoch)

        head.train()
        total_loss = 0.0
        num_steps = 0

        for batch in loader:
            with accelerator.accumulate(head):
                videos = batch["video"]
                depths = batch["depth"]

                min_frames = min(len(v) for v in videos)
                if any(len(v) != min_frames for v in videos):
                    videos = [v[:min_frames] for v in videos]
                    depths = [d[:, :min_frames] for d in depths]

                if any(d is None for d in depths):
                    raise RuntimeError("Depth tensor is missing from the dataset. Check dataset_geometry_path and npz format.")

                video_latents = encode_video_to_latents(videos)
                depth_stack = torch.stack([d for d in depths], dim=0).to(device=accelerator.device, dtype=pipe.torch_dtype)
                depth_latents = encode_depth_to_latents(depth_stack)

                pred_depth_latents = head(video_latents.float())
                loss = loss_fn(pred_depth_latents, depth_latents.float())

                accelerator.backward(loss)
                optimizer.step()
                optimizer.zero_grad(set_to_none=True)

            total_loss += float(loss.detach().item())
            num_steps += 1

        mean_loss = total_loss / max(1, num_steps)
        accelerator.print(f"Epoch {epoch} | loss={mean_loss:.6f}")

        if epoch % int(args.save_every_epochs) == 0:
            from safetensors.torch import save_file

            state = accelerator.get_state_dict(head)
            save_path = os.path.join(args.output_path, f"epoch-{epoch}.safetensors")
            if accelerator.is_main_process:
                save_file(state, save_path)
                with open(os.path.join(args.output_path, "train_config.json"), "w", encoding="utf-8") as f:
                    json.dump({
                        "model_id": args.model_id,
                        "model_root": args.model_root,
                        "dataset_base_path": args.dataset_base_path,
                        "dataset_geometry_path": args.dataset_geometry_path,
                        "dataset_metadata_path": args.dataset_metadata_path,
                        "height": int(args.height),
                        "width": int(args.width),
                        "num_frames": int(args.num_frames),
                        "hidden_channels": int(args.hidden_channels),
                    }, f, ensure_ascii=False, indent=2)
            accelerator.wait_for_everyone()

    accelerator.print(f"Done. Outputs: {args.output_path}")


if __name__ == "__main__":
    main()
